version: 2
jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install codecov coverage

      - run:
          name: run tests
          command: coverage run main.py
          