version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install --user codecov coverage

      - run:
          name: run tests
          command: python -m coverage run main.py
          